name: Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.5

    - name: Build
      run: go build -o main

    - name: Run Application
      run: ./main
      env: 
        PORT: ${{ secrets.PORT }}
        JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
